In [1]:
import numpy as np
import matplotlib.pyplot as plt
import joblib
import pandas as pd

In [36]:
class Perceptron:
    def __init__(self, eta, epochs) : # eta --> learning rate, epochs --> iteration
        self.weights = np.random.randn(3) * 1e-4
        print(f"self.weights: {self.weights}")
        self.eta = eta
        self.epochs = epochs

    def activationFunction(self, inputs, weights) :
        z = np.dot(inputs, weights)
        return np.where(z > 0, 1, 0)

    def fit(self, X, y) :
        self.X = X
        self.y = y

        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X_with_bias : \n{X_with_bias}")

        for epoch in range(self.epochs) :
            print(f"For epoch : {epoch}")
            y_hat = self.activationFunction(X_with_bias, self.weights)
            print(f"Predicted Value : \n{y_hat}")
            error = self.y - y_hat
            print(f"error : \n{error}")
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, error)
            print(f"updated weights : \n{self.weights}")

    def predict(self, X) :
        X_with_bias = np.c_[X, -np.ones((len(self.X), 1))]
        return self.activationFunction(X_with_bias, self.weights)

## AND

In [37]:
data = {'x1' : [0,0,1,1], 'x2' : [0,1,0,1], 'y' : [0,0,0,1]}

AND = pd.DataFrame(data)
AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [50]:
X = AND.drop('y', axis = 1)
y = AND['y']

In [39]:
model = Perceptron(eta = 0.5, epochs = 10)
model.fit(X, y)

self.weights: [ 2.20778833e-05 -9.49298054e-05  2.44588603e-05]
X_with_bias : 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
For epoch : 0
Predicted Value : 
[0 0 0 0]
error : 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights : 
[ 0.50002208  0.49990507 -0.49997554]
For epoch : 1
Predicted Value : 
[1 1 1 1]
error : 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights : 
[ 2.20778833e-05 -9.49298054e-05  1.00002446e+00]
For epoch : 2
Predicted Value : 
[0 0 0 0]
error : 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights : 
[0.50002208 0.49990507 0.50002446]
For epoch : 3
Predicted Value : 
[0 0 0 1]
error : 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights : 
[0.50002208 0.49990507 0.50002446]
For epoch : 4
Predicted Value : 
[0 0 0 1]
error : 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights : 
[0.50002208 0.49990507 0.50002446]
For epoch : 5
Predicted Value : 
[0 0 0 1]
error : 
0    0
1  

In [40]:
model.predict(X)

array([0, 0, 0, 1])

In [41]:
model.weights

array([0.50002208, 0.49990507, 0.50002446])

## OR

In [42]:
data = {'x1' : [0,0,1,1], 'x2' : [0,1,0,1], 'y' : [0,1,1,1]}

OR = pd.DataFrame(data)
OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [49]:
X = OR.drop('y', axis = 1)
y = OR['y']

In [44]:
model = Perceptron(eta = 0.5, epochs = 10)
model.fit(X, y)

self.weights: [-2.33911621e-05  4.69017818e-05 -1.97632515e-05]
X_with_bias : 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
For epoch : 0
Predicted Value : 
[1 1 0 1]
error : 
0   -1
1    0
2    1
3    0
Name: y, dtype: int64
updated weights : 
[ 4.99976609e-01  4.69017818e-05 -1.97632515e-05]
For epoch : 1
Predicted Value : 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights : 
[4.99976609e-01 4.69017818e-05 4.99980237e-01]
For epoch : 2
Predicted Value : 
[0 0 0 1]
error : 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights : 
[ 0.99997661  0.5000469  -0.50001976]
For epoch : 3
Predicted Value : 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights : 
[ 9.99976609e-01  5.00046902e-01 -1.97632515e-05]
For epoch : 4
Predicted Value : 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights : 
[0.99997661 0.5000469  0.49998024]
For epoch : 5
Predicted Value : 
[0

In [46]:
model.predict(X)

array([0, 1, 1, 1])

In [47]:
model.weights

array([0.99997661, 0.5000469 , 0.49998024])

## XOR

In [48]:
data = {'x1' : [0,0,1,1], 'x2' : [0,1,0,1], 'y' : [0,1,1,0]}

XOR = pd.DataFrame(data)
XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [51]:
X = XOR.drop('y', axis = 1)
y = XOR['y']

In [52]:
model = Perceptron(eta = 0.5, epochs = 10)
model.fit(X, y)

self.weights: [-2.10833618e-04  3.42890887e-05  3.47594682e-05]
X_with_bias : 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
For epoch : 0
Predicted Value : 
[0 0 0 0]
error : 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights : 
[ 0.49978917  0.50003429 -0.99996524]
For epoch : 1
Predicted Value : 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights : 
[-2.10833618e-04  3.42890887e-05  3.47594682e-05]
For epoch : 2
Predicted Value : 
[0 0 0 0]
error : 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights : 
[ 0.49978917  0.50003429 -0.99996524]
For epoch : 3
Predicted Value : 
[1 1 1 1]
error : 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights : 
[-2.10833618e-04  3.42890887e-05  3.47594682e-05]
For epoch : 4
Predicted Value : 
[0 0 0 0]
error : 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights : 
[ 0.49978917  0.50003429 -0.99996524]
For epoch : 5
Predicted Value : 
[1 1 1 1

In [53]:
model.predict(X)

array([0, 0, 0, 0])

In [54]:
model.weights

array([-2.10833618e-04,  3.42890887e-05,  3.47594682e-05])